from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from typing import List, Optional
import redis
import os
import uuid
import json

from . import models, database
from .database import engine, get_db

models.Base.metadata.create_all(bind=engine)

app = FastAPI(title="Industrial Attendance Service")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Redis for short-lived mobile sessions
redis_client = redis.from_url(os.getenv("REDIS_URL", "redis://redis:6379/0"))

@app.get("/")
def read_root():
    return {"service": "Attendance Service", "status": "online"}

# --- Mobile Verification Sessions ---

import socket

def get_local_ip():
    """Returns the host machine's LAN IP, prioritizing the HOST_IP env var set by the deploy script."""
    host_ip = os.getenv("HOST_IP")
    if host_ip:
        return host_ip
        
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        # doesn't even have to be reachable
        s.connect(('8.8.8.8', 1))
        IP = s.getsockname()[0]
    except Exception:
        IP = '127.0.0.1'
    finally:
        s.close()
    return IP

@app.post("/attendance/session/create")
def create_verification_session(type: str = "VERIFY"):
    """
    Generated by Laptop. type can be 'VERIFY' or 'ENROLL'.
    """
    session_id = str(uuid.uuid4())
    # Store session in Redis with 10 minute expiry for enrollment
    session_data = {
        "status": "PENDING", 
        "type": type,
        "user_id": None,
        "captured_data": {
            "profile_photo": False,
            "face_encoding": False,
            "fingerprint": False
        }
    }
    expiry = 600 if type == "ENROLL" else 300
    redis_client.setex(f"session:{session_id}", expiry, json.dumps(session_data))
    
    return {
        "session_id": session_id,
        "server_ip": get_local_ip()
    }

@app.post("/attendance/session/{session_id}/update-enrollment")
def update_enrollment_progress(session_id: str, field: str):
    """
    Called by Mobile to signal a step is done.
    """
    data = redis_client.get(f"session:{session_id}")
    if not data:
        raise HTTPException(status_code=404, detail="Session expired")
    
    session_data = json.loads(data)
    if "captured_data" in session_data:
        session_data["captured_data"][field] = True
        redis_client.setex(f"session:{session_id}", 600, json.dumps(session_data))
    return {"status": "Updated", "progress": session_data["captured_data"]}

@app.get("/attendance/session/{session_id}")
def get_session_status(session_id: str):
    """
    Called by Laptop (polling) to see if phone has verified.
    """
    data = redis_client.get(f"session:{session_id}")
    if not data:
        raise HTTPException(status_code=404, detail="Session expired or not found")
    return json.loads(data)

from datetime import datetime
from sqlalchemy import func

from sqlalchemy import extract

@app.get("/attendance/stats/overview")
def get_stats_overview(db: Session = Depends(get_db)):
    """
    Returns deep industrial analytics and KPIs.
    """
    now = datetime.now()
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    
    # 1. Workforce Engagement
    total_users = db.query(models.User).count()
    present_today = db.query(models.Attendance.user_id).filter(
        models.Attendance.timestamp >= today_start
    ).distinct().count()
    engagement_rate = (present_today / total_users * 100) if total_users > 0 else 0

    # 2. Punctuality (Assume 09:00 AM shift start)
    cutoff = today_start.replace(hour=9)
    late_count = db.query(models.Attendance).filter(
        models.Attendance.timestamp > cutoff,
        models.Attendance.status == "CHECK_IN"
    ).count()
    on_time_count = present_today - late_count
    punctuality_rate = (on_time_count / present_today * 100) if present_today > 0 else 100

    # 3. Model Consistency (Standard Deviation of AI Confidence)
    # Smaller variance = more stable environment
    std_dev_confidence = db.query(func.stddev(models.Attendance.confidence_score)).filter(
        models.Attendance.confidence_score.isnot(None)
    ).scalar() or 0.0

    # 4. Departmental Breakdown (using JOIN)
    dept_stats = db.query(
        models.User.department, 
        func.count(models.Attendance.id)
    ).join(models.Attendance, models.User.id == models.Attendance.user_id).filter(
        models.Attendance.timestamp >= today_start
    ).group_by(models.User.department).all()
    
    # 5. Peak Traffic Analysis (Hourly distribution)
    hourly_traffic = db.query(
        extract('hour', models.Attendance.timestamp).label('hour'),
        func.count(models.Attendance.id)
    ).filter(
        models.Attendance.timestamp >= today_start
    ).group_by('hour').all()

    # 6. Method Counts
    face_count = db.query(models.Attendance).filter(models.Attendance.method == "FACE").count()
    mobile_count = db.query(models.Attendance).filter(models.Attendance.method == "MOBILE_BIOMETRIC").count()

    return {
        "present_today": present_today,
        "total_registered": total_users,
        "engagement_rate": round(engagement_rate, 1),
        "punctuality_rate": round(punctuality_rate, 1),
        "model_stability": round(1 - (float(std_dev_confidence) * 2), 4), # Normalized stability score
        "ai_confidence_index": round(float(db.query(func.avg(models.Attendance.confidence_score)).scalar() or 0.0), 4),
        "department_distribution": {dept: count for dept, count in dept_stats},
        "hourly_peaks": {int(h): c for h, c in hourly_traffic},
        "total_logs": db.query(models.Attendance).count(),
        "method_distribution": {"FACE": face_count, "MOBILE": mobile_count},
        "system_status": "Operational"
    }

@app.post("/attendance/session/{session_id}/verify")
def verify_session(session_id: str, user_id: int, db: Session = Depends(get_db)):
    """
    Called by Mobile Phone after biometric check.
    """
    # 1. Update Redis state
    session_data = {"status": "VERIFIED", "user_id": user_id}
    redis_client.setex(f"session:{session_id}", 300, json.dumps(session_data))
    
    # 2. Automatically log attendance
    new_record = models.Attendance(
        user_id=user_id, 
        status="CHECK_IN", 
        method="MOBILE_BIOMETRIC",
        device="USER_SMARTPHONE",
        confidence_score=0.0 # Mobile auth is usually 1:1 local, so we treat as high confidence
    )
    db.add(new_record)
    db.commit()
    db.refresh(new_record)
    
    return {"message": "Verified successfully", "attendance_id": new_record.id}

# --- Standard Logs ---

@app.post("/attendance/log")
def log_attendance(
    user_id: int, 
    status: str = "CHECK_IN", 
    method: str = "FACE", 
    device: Optional[str] = None,
    confidence_score: Optional[float] = None,
    db: Session = Depends(get_db)
):
    new_record = models.Attendance(
        user_id=user_id, 
        status=status, 
        method=method,
        device=device,
        confidence_score=confidence_score
    )
    db.add(new_record)
    db.commit()
    db.refresh(new_record)
    return new_record

@app.get("/attendance/{user_id}")
def get_user_attendance(user_id: int, db: Session = Depends(get_db)):
    records = db.query(models.Attendance).filter(models.Attendance.user_id == user_id).all()
    return [{
        "id": r.id, 
        "timestamp": r.timestamp, 
        "status": r.status,
        "method": r.method,
        "device": r.device
    } for r in records]
